---
- name: Create a backup of teksts.txt
  hosts: 192.168.0.205
  tasks:
    - name: Get the current date
      shell: date +%H-%M-%d-%m-%y
      register: backup_date

    - name: Create a backup file
      copy:
        src: faili/teksts
        remote_src: yes
        dest: backup/teksts-{{ backup_date.stdout }}
        owner: root
        group: root
        mode: 0644
