---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  vars:
    database_name: tests10
    backup_directory: /var/lib/mysql/backup

  tasks:
    - name: Create the backup directory
      file:
        path: "{{ backup_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Backup MySQL database
      copy:
        src: /var/lib/mysql/"{{ database_name }}"
        remote_src: yes
        dest: "{{ backup_directory }}"
        register: backup_result
        owner: root
        group: root
        mode: 0644

    - name: Check backup results
      fail: msg="{{ backup_result.stderr }}"
      when: backup_result.rc != 0
