---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  tasks:
  
    - name: Create a backup directory
      file:
        path: /var/lib/mysql/backup
        state: directory
        shell: date +%H-%M-%d-%m-%y
        register: backup_date
        
    - name: Dump database
      shell: "mysqldump -u rolands tests10 > backup/tests10-{{ back_date.stdout }}.sql"
