---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  tasks:
    - name: Stop MySQL service
      service:
        name: mysql
        state: stopped

    - name: Create a backup directory
      file:
        path: /var/lib/mysql/backup
        state: directory
        
    - name: Create MySQL database backup
      command: sudo mysqldump -u root -p tests10 > /var/lib/mysql/backup/tests - "+%H-%M-%d-%m-%y".sql

    - name: Start MySQL service
      service:
        name: mysql
        state: started
