---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  vars:
    database_name: tests10
    backup_directory: /var/lib/mysql/backup

  tasks:
    - name: Create the backup directory
      file:
        path: "{{ backup_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Backup MySQL database
      command: mysqldump -u root -p "{{ database_name }}" > "{{ backup_directory }}/{{ database_name }}.sql"
      register: backup_result

    - name: Check backup results
      fail: msg="{{ backup_result.stderr }}"
      when: backup_result.rc != 0
