---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  tasks:
    - name: Stop MySQL service
      service:
        name: mysql
        state: stopped

    - name: Create a backup directory
      file:
        path: /var/lib/mysql/backup
        state: directory

    - name: Backup the tests10 database
      mysql_dump:
        database: tests10
        target: /var/lib/mysql/backup/tests10-$(date +%Y-%m-%d-%H-%M).sql

    - name: Start MySQL service
      service:
        name: mysql
        state: started
