---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  tasks:
    - name: Backup MySQL database
      command: mysqldump -u root -p tests10 > /tmp/tests10.sql

    - name: Copy backup to remote server
      copy:
        src: /tmp/tests10.sql
        dest: /srv/backups/tests10.sql
        remote_src: yes
        
  handlers:
    - name: Restart MySQL server
      service:
        name: mysql
        state: restarted
