---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  tasks:
  
    - name: Create a backup directory
      file:
        path: /var/lib/mysql/backup
        state: directory
        
    - name: Create MySQL database backup
      command: mysqldump -u rolands -p tests10 > backup/tests.sql
