---
- name: Create MySQL database backup
  hosts: all
  become: yes
  vars:
    db_name: tests10
    backup_dir: /backups

  tasks:
    - name: Create backup file
      copy:
        content: "{{ lookup('template', './db_backup.sql') }}"
        dest: "{{ backup_dir }}/{{ db_name }}_backup.sql"
        
  handlers:
    - name: Restart MySQL server
      service:
        name: mysql
        state: restarted
