---
- name: Create MySQL database backup
  hosts: all
  become: yes
  vars:
    db_name: tests10
    backup_dir: /backups

  tasks:
    - name: Create backup file
      copy:
        content: "{{ lookup('template', './db_backup.sql') }}"
        dest: "{{ backup_dir }}/{{ db_name }}_backup.sql"

    - name: Back up the database
      mysql_db:
        state: backup
        db: "{{ db_name }}"
        backup_path: "{{ backup_dir }}/{{ db_name }}_backup.sql"
        owner: root
        group: root
        mode: 0600
        
  handlers:
    - name: Restart MySQL server
      service:
        name: mysql
        state: restarted
