---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  tasks:
    - name: Stop MySQL service
      service:
        name: mysql
        state: stopped

    - name: Create a backup directory
      file:
        path: /var/lib/mysql/backup
        state: directory

    - name: Copy database dump file
      copy:
        src: tests10.sql.bz2
        dest: /var/lib/mysql/backup

    - name: Start MySQL service
      service:
        name: mysql
        state: started
