---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  tasks:
  
    - name: Create a backup directory
      file:
        path: /var/lib/mysql/backup
        state: directory
    - name: Dump database
      community.mysql.mysql_db:
        state: dump
        name: tests10
        target: /backup/tests11.sql
