---
- name: Create MySQL database backup
  hosts: 192.168.0.205
  become: yes
  vars:
    db_name: tests10
    backup_dir: /backups

  tasks:
    - name: Create backup file
      copy:
        src: "/var/lib/mysql/{{ db_name }}.dump.gz"
        dest: "{{ backup_dir }}/{{ db_name }}_backup.sql"
        
  handlers:
    - name: Restart MySQL server
      service:
        name: mysql
        state: restarted
