---
- hosts: 192.168.0.205
  become: true
  vars:
    database_name: tests10
    backup_file: /var/lib/mysql/backup/"{{ database_name }}".sql

  tasks:
    - name: Restore MySQL database
      command: sudo mysql -u root -p "{{ database_name }}" < "{{ backup_file }}"
