---
- name: Update AlmaLinux server
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure dnf is up to date
      yum:
        update_cache: yes
        state: latest

    - name: Update AlmaLinux to latest version
      yum:
        update: yes
        state: latest

    - name: Reboot AlmaLinux server
      reboot:
        reboot_timeout: 600
