---
- name: Update AlmaLinux server to latest version
  hosts: all
  become: yes

  tasks:

    - name: Update AlmaLinux package repositories
      yum:
        update_cache: yes

    - name: Install the latest AlmaLinux package updates
      yum:
        update: yes
        name: '*'
        state: latest
        enablerepo: '*'

    - name: Reboot the server to apply updates
      reboot:
        reboot_timeout: 600
        reboot_required: yes
      when: ansible_status.rc == 0
