---
- name: Update and restart Ubuntu machines
  hosts: all
  become: yes
  tasks:
    - name: Update Ubuntu packages
      apt:
        update_cache: true
        upgrade: yes
        force_yes: yes
        verbose: yes
    - name: Restart restarted services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - sshd
        - network-manager
      register: restart_results

    - name: Display restart results
      debug:
        msg: "{{ restart_results }}"
