---
- name: Update and upgrade Ubuntu packages
  hosts: all
  become: yes
  ignore_unreachable: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

- name: Reboot the server
  hosts: all
  become: yes
  ignore_unreachable: yes
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 3600
