---
- hosts: all
  become: yes

  tasks:

    - name: Update AlmaLinux 9
      dnf:
        name: '*'
        state: latest
        
    - name: Reboot remote server
      reboot:
            reboot_timeout: 300
