---
- name: Update Ubuntu packages
  hosts: all
  become: yes
  tasks:
  - name: Update apt package cache
    apt:
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: yes

  - name: Reboot the server
    reboot:

  - name: Login after reboot
    become: yes
    user: "{{ ansible_user }}"
    connection: ssh
    shell: "echo 'Logged in!'"
