---
- hosts: all
  become: yes

  tasks:
    - name: Create a backup directory
      file:
        path: /root/backup
        state: directory
    - name: Backup important files
      synchronize:
        src: "/etc/"
        dest: "/root/backup/backup-{{ ansible_date_time.iso8601 }}/"
        archive: yes
        
    - name: Update AlmaLinux 9
      dnf:
        name: '*'
        state: latest
        
    - name: Reboot remote server
      reboot:
            reboot_timeout: 300
