---
- name: Update AlmaLinux server to latest version
  hosts: all
  connection: network_cli
  become: yes
  gather_facts: no
  tasks:
  - name: Check if AlmaLinux is up to date
    shell: dnf --quiet --refresh --assumeyes list updates
    register: updates
    failed_when: updates.rc != 0

  - name: Update AlmaLinux to latest version
    shell: dnf --quiet --refresh --assumeyes upgrade
    register: upgrade
    failed_when: upgrade.rc != 0

  - name: Reboot AlmaLinux server
    shell: reboot
    name: Reboot
    when: upgrade.rc == 0
