---
- hosts: all
  become: yes

  tasks:
    - name: Create a backup of important files
      command: "tar czf /root/backup/{{ ansible_date_time.date }}_backup.tar.gz /"
      ignore_errors: yes
        
    - name: Update AlmaLinux 9
      dnf:
        name: '*'
        state: latest
        
    - name: Reboot remote server
      reboot:
            reboot_timeout: 300
