---
- name: Update Ubuntu machines
  hosts: all
  become: yes
  ignore_unreachable: yes
  tasks:
  - name: Update system packages
    apt:
      update_cache: yes
      upgrade: yes
      autoremove: yes
    register: updated_packages

  - name: Print updated packages
    debug:
      var: updated_packages.stdout_lines

- name: Reboot the server
  hosts: all
  become: yes
  ignore_unreachable: yes
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 3600
