---
- hosts: all
  become: yes

  tasks:
    - name: Perform a full system update
      yum:
        name: '*'
        state: latest
      register: update_result
    - name: Show the update result
      debug:
        var: update_result
        
    - name: Reboot remote server
      reboot:
            reboot_timeout: 300
