---
- name: Update AlmaLinux Server to Latest Version
  hosts: all
  become: true
  tasks:
    - name: Update AlmaLinux packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Reboot AlmaLinux Server
      reboot:
        reboot_timeout: 600
