---
- name: Update and restart Ubuntu machines
  hosts: all
  become: yes
  tasks:
    - name: Update Ubuntu packages
      apt:
        update_cache: true
        upgrade: yes

 # Print verbose output
  - name: Print verbose output
    debug:
      msg: "{{ apt_output }}"
      when: apt_result.changed

  # Restart services after update
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items: "{{ update_result.results | flatten('items') | map(attribute='service') | unique }}"
    - name: Display restart results
      debug:
        msg: "{{ restart_results }}"
