---
- name: Update Ubuntu packages and log in user after reboot
  hosts: all
  become: yes
  tasks:
  - name: Update apt package cache
    apt:
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: yes

  - name: Reboot the server
    reboot:
      reboot_timeout: 600

  - name: Log in the user after reboot
    shell: "sudo su - {{ansible_user}}"
  become_user: true
