---
- name: Update Ubuntu machines
  hosts: all
  become: yes
  tasks:
  - name: Update system packages
    apt:
      update_cache: yes
      upgrade: yes
      autoremove: yes
    register: updated_packages

  - name: Print updated packages
    debug:
      var: updated_packages.stdout_lines

  - name: Restart services
    service:
      name: "{{ service_name }}"
      state: restarted
    with_items:
      - nginx
      - httpd
      - mysql
