---
- name: Update and upgrade Ubuntu packages
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

- name: Reboot the server
  hosts: all
  become: yes
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 3600

- name: Log the user back in after reboot
  hosts: all
  become: yes
  tasks:
    - name: Log in as the default user
      shell: "sudo su -"
      become_user: root
