---
- hosts: all
  become: yes

  tasks:
    - name: Create a backup of important files
      command: "tar -cvzf /root/backup_{{ ansible_date_time.iso8601 }}.tar.gz /root"
      register: backup_result
      ignore_errors: yes
        
    - name: Update AlmaLinux 9
      dnf:
        name: '*'
        state: latest
        
    - name: Reboot remote server
      reboot:
            reboot_timeout: 300
