---
- name: Update and upgrade Ubuntu packages
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

- name: Reboot the server
  hosts: all
  become: yes
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 3600

- name: Log the user back in after reboot
  hosts: all
  become: yes
  tasks:
    - name: Execute command to log the user back in after reboot
      shell: |
        su - {{ ansible_user }} << EOF
        export DISPLAY=:0
        gnome-session-ctl restart
        EOF
      become_user: "{{ ansible_user }}"
