---
- hosts: all
  become: yes

  tasks:
    - name: Create a backup
      archive:
        path: /root
        dest: /root/backup-{{ ansible_date_time.date }}.tar.gz
        
    - name: Update AlmaLinux 9
      dnf:
        name: '*'
        state: latest
        
    - name: Reboot remote server
      reboot:
            reboot_timeout: 300
