---
- name: Update and upgrade Ubuntu packages
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

- name: Reboot the server
  hosts: all
  become: yes
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 3600

- name: Relogin the user after reboot
  hosts: all
  become: yes
  tasks:
    - name: Get current user
      shell: whoami
      register: current_user

    - name: Get ansible user
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        state: present
        shell: /bin/bash
        createhome: yes

    - name: Log the user in after reboot
      shell: su - "{{ current_user.stdout }}"
