---
- name: Update and upgrade Ubuntu packages
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

- name: Reboot the server
  hosts: all
  become: yes
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 3600

- name: Login as user after reboot
  hosts: all
  become: yes
  tasks:
    - name: Login as user '{{ ansible_user }}'
      shell: "su - {{ ansible_user }}"
