---
- name: Update AlmaLinux server to latest version
  become: true
  hosts: all
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become_user: root
    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
      become_user: root

- name: Reboot AlmaLinux server
  become: true
  hosts: all
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 600
        force: yes
