---
- name: Update Ubuntu machines
  hosts: all
  become: yes
  tasks:
  - name: Update package lists
    apt:
      update_cache: yes
      force_apt_get: yes
    become_verbose: yes

  - name: Upgrade installed packages
    apt:
      upgrade: yes
      autoclean: yes
      autoremove: yes
    become_verbose: yes

  - name: Restart all services
    service:
      name: "*"
      state: restarted
    become_verbose: yes

- name: Display updated packages
  hosts: all
  become: yes
  tasks:
  - name: Get updated package list
    shell: apt list --installed --upgradable
    become_verbose: yes
