---
- name: Update AlmaLinux server to latest version
  hosts: all
  become: true
  tasks:
    # Update the system
    - name: Update AlmaLinux packages
      yum:
        update_cache: yes
        upgrade: yes
        name: '*'
        state: latest
        exclude: 'kernel*'

    # Reboot the server to apply the updates
    - name: Reboot the server
      reboot:
        reboot_timeout: 600
