---
- name: Update AlmaLinux server
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update system packages
      yum:
        update_cache: yes
        packages: '*'
        state: latest
        disable_gpg_check: yes

    - name: Reboot AlmaLinux server
      reboot:
        reboot_timeout: 600
